### PR TITLE
Better support all unix platforms.

### LINKED ISSUE #7: Support 32bit Linux
This shouldn't be difficult but I can't test it so I can't just submit a pull request.

### PR DESCRIPTION
**Pull request by Stebalien**
This includes 32bit linux which previously used the fallback lock.

Closes #7

Note: I've only tested this on 64bit linux.

### CODE REVIEW

**Comment by Stebalien** [comment]
@bradfitz ping.

**Comment by bradfitz** [comment]
Have you submitted a CLA?

We'd also want this tested everywhere first.

Perhaps we should move it into golang.org/x/* (maybe in tools?) so we can use the cross-platform trybots.

/cc @mpl @adg

**Comment by Stebalien** [comment]
The google CLA? Yes.

**Comment by mpl** [comment]
We/I can at least test it on linux_arm if that helps ?

**Comment by Stebalien** [comment]
ping

**Comment by bradfitz** [comment]
@mpl, we should move this to go4.org and delete this repo.

**Comment by mpl** [comment]
ACK

**Comment by Stebalien** [comment]
Moved to https://github.com/camlistore/go4/pull/14

**Pull request closed without merging**
